version: 0.1
phases:
  install:
    commands:
      - echo "install step"
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
      - echo "pre_build step"
      - echo "installing dependencies"
      - npm install -g next
      - npm i
      - echo "building static content"
      - npm run build
  post_build:
    commands:
      - echo "post_build step"
      - echo "coping files to s3"
      - aws s3 sync --delete ./out "s3://virtualcomics.com"
